In [2]:
import pandas as pd
import numpy as np
import time

In [16]:
class DCModel:

    def __init__(self, path):
        self.df = pd.read_csv(path, sep='\t')
        self.name = self.df['name'].tolist()
        self.all_name = self.df['name'].tolist() + self.aliases()

    def __len__(self):
        return self.df.__len__()

    def names(self):
        return self.name

    def aliases(self):
        al = []
        for i in self.df['aliases'].unique():
            if not pd.isna(i):
                al += i.split('|')
        return al

    def has(self, name):
        if name in self.all_names:
            return True
        else:
            return False

    def find(self, keyword):
        # fuzzy match
        r_n = self.df[self.df['name'].str.find(keyword) == 0]
        r_a = self.df[self.df['aliases'].str.find(keyword) == 0]
        if r_n.__len__() != 0:
            return r_n['name'].values[0]
        elif r_a.__len__() != 0:
            return r_a['name'].values[0]
        else:
            return None

    def find_exact(self, keyword):
        # exact match
        r_n = self.df[self.df['name'] == keyword]
        r_a = self.df[self.df['aliases'] == keyword]
        if r_n.__len__() != 0:
            return r_n['name'].values[0]
        elif r_a.__len__() != 0:
            return r_a['name'].values[0]
        else:
            return None
        
    def add(self, name, status='new', comment=np.nan, aliases=np.nan):
        self.df = self.df.append({'name': str(name),
                                  'status': status,
                                  'comment': comment,
                                  'aliases': aliases
                                  }, ignore_index=True).copy()
    
    def to_csv(self, path):
        self.df.to_csv('path', sep='\t', index=False)
        

    
celllines = DCModel('../celllines.txt')

In [17]:
class DCJournal:

    def __init__(self, path):
        self.df = pd.read_csv(path, sep='\t')
        self.name = self.df['name'].tolist()

    def __len__(self):
        return self.df.__len__()

    def names(self):
        return self.name

    def has(self, name):
        if name in self.name:
            return True
        else:
            return False

    def find(self, keyword):
        # fuzzy match
        r_n = self.df[self.df['name'].str.find(keyword) == 0]
        if r_n.__len__() != 0:
            return r_n['name'].values[0]
        else:
            return None
        
    def find_exact(self, keyword):
        # exact match
        r_n = self.df[self.df['name'] == keyword]
        if r_n.__len__() != 0:
            return r_n['name'].values[0]
        else:
            return None

    def add(self, name, issn=np.nan, impact_factor=np.nan):
        self.df = self.df.append({'name': str(name),
                                  'issn': issn,
                                  'impact_factor': impact_factor
                                  }, ignore_index=True).copy()
    
    def to_csv(self, path):
        self.df.to_csv('path', sep='\t', index=False)
        
journal = DCJournal('../journals.txt')

In [30]:
journal.find('Nucleic')

'Nucleic Acids Res.'

In [97]:
class DCPaper:

    def __init__(self, path):
        self.df = pd.read_csv(path, sep='\t')
        self.pmid = self.df['pmid'].tolist()

    def __len__(self):
        return self.df.__len__()

    def has(self, pmid):
        if pmid in self.pmid:
            return True
        else:
            return False

#     def find(self, keyword):
#         # fuzzy match
#         r_n = self.df[self.df['name'].str.find(keyword) == 0]
#         if r_n.__len__() != 0:
#             return r_n['name'].values[0]
#         else:
#             return None

    def find_exact(self, keyword):
        # exact match
        r_n = self.df[self.df['pmid'] == keyword]
        if r_n.__len__() != 0:
            return list(r_n.T.to_dict().items())[0][1]
        else:
            return None

    def add(self, pmid=np.nan, unique_id=np.nan, title=np.nan,
            reference=np.nan, abstract=np.nan, pub_date=np.nan,
            collect_date=np.nan, authors=np.nan, last_auth_email=np.nan,
            journal=np.nan, status='new', lab=np.nan,
            pub_summary=np.nan, comment=np.nan):
        self.df = self.df.append({'pmid': str(pmid),
                                  'unique_id': unique_id,
                                  'title': title,
                                  'reference': reference,
                                  'abstract': abstract,
                                  'pub_date': pub_date,
                                  'collect_date': collect_date,
                                  'authors': authors,
                                  'last_auth_email': last_auth_email,
                                  'journal': journal,
                                  'status': status,
                                  'lab': lab,
                                  'pub_summary': pub_summary,
                                  'comment': comment,
                                  }, ignore_index=True).copy()

    def to_csv(self, path):
        self.df.to_csv(path, sep='\t', index=False)
        
papers = DCPaper('../papers.txt')

In [ ]:
pmid	unique_id	title	reference	abstract	pub_date	collect_date	authors	last_auth_email	journal	status	lab	pub_summary	comment

In [98]:
papers.find_exact('20508144')

{'pmid': '20508144',
 'unique_id': 'GSE20478',
 'title': 'A global role for KLF1 in erythropoiesis revealed by ChIP-seq in primary erythroid cells.',
 'reference': 'Tallack MR, et al. A global role for KLF1 in erythropoiesis revealed by ChIP-seq in primary erythroid cells. Genome Res. 2010',
 'abstract': 'KLF1 regulates a diverse suite of genes to direct erythroid cell differentiation from bipotent progenitors. To determine the local cis-regulatory contexts and transcription factor networks in which KLF1 operates, we performed KLF1 ChIP-seq in the mouse. We found at least 945 sites in the genome of E14.5 fetal liver erythroid cells which are occupied by endogenous KLF1. Many of these recovered sites reside in erythroid gene promoters such as Hbb-b1, but the majority are distant to any known gene. Our data suggests KLF1 directly regulates most aspects of terminal erythroid differentiation including production of alpha- and beta-globin protein chains, heme biosynthesis, coordination of proliferation and anti-apoptotic pathways, and construction of the red cell membrane and cytoskeleton by functioning primarily as a transcriptional activator. Additionally, we suggest new mechanisms for KLF1 cooperation with other transcription factors, in particular the erythroid transcription factor GATA1, to maintain homeostasis in the erythroid compartment.',
 'pub_date': '2010/8/3',
 'collect_date': '2011/12/7 09:55:09',
 'authors': 'Tallack MR, Whitington T, Yuen WS, Wainwright EN, Keys JR, Gardiner BB, Nourbakhsh E, Cloonan N, Grimmond SM, Bailey TL, Perkins AC',
 'last_auth_email': 'a.perkins@imb.uq.edu.au',
 'journal': 'Genome Res.',
 'status': 'imported',
 'lab': 'Perkins AC',
 'pub_summary': 'Tallack MR, et al. Genome Res. 2010',
 'comment': nan}

In [99]:
papers.df

,pmid,unique_id,title,reference,abstract,pub_date,collect_date,authors,last_auth_email,journal,status,lab,pub_summary,comment
0,20208068,GSE17937,Comparing genome-wide chromatin profiles using...,"Johannes F, et al. Comparing genome-wide chrom...",ChIP-chip and ChIP-seq technologies provide ge...,2010/4/14,2011/12/7 09:55:04,"Johannes F, Wardenaar R, Colomé-Tatché M, Mous...",f.johannes@rug.nl,Bioinformatics,datasets,Jansen RC,"Johannes F, et al. Bioinformatics 2010",NaN
1,20690147,GSE21665,Global analysis of in vivo EGR1-binding sites ...,"Tang C, et al. Global analysis of in vivo EGR1...",Early growth response gene 1 (EGR1) has been i...,2010/9/13,2011/12/7 09:55:06,"Tang C, Shi X, Wang W, Zhou D, Tu J, Xie X, Ge...",Zen.Lu@unisa.edu.au,Electrophoresis,imported,Lu Z,"Tang C, et al. Electrophoresis 2010",NaN
2,21152096,GSE18481,Efficient double fragmentation ChIP-seq provid...,"Mokry M, et al. Efficient double fragmentation...",Immunoprecipitated crosslinked protein-DNA fra...,2010/12/14,2011/12/7 09:55:07,"Mokry M, Hatzis P, de Bruijn E, Koster J, Vers...",e.cuppen@hubrecht.e,PLoS ONE,imported,Cuppen E,"Mokry M, et al. PLoS ONE 2010",NaN
3,20508144,GSE20478,A global role for KLF1 in erythropoiesis revea...,"Tallack MR, et al. A global role for KLF1 in e...",KLF1 regulates a diverse suite of genes to dir...,2010/8/3,2011/12/7 09:55:09,"Tallack MR, Whitington T, Yuen WS, Wainwright ...",a.perkins@imb.uq.edu.au,Genome Res.,imported,Perkins AC,"Tallack MR, et al. Genome Res. 2010",NaN
4,21423270,GSE26005,The human TTAGGG repeat factors 1 and 2 bind t...,"Simonet T, et al. The human TTAGGG repeat fact...",The study of the proteins that bind to telomer...,2011/7/4,2012/3/8 14:21:24,"Simonet T, Zaragosi LE, Philippe C, Lebrigand ...",NaN,Cell Res.,imported,Gilson E,"Simonet T, et al. Cell Res. 2011",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4110,31434493,200131212,Epigenetic Regulation of Vascular Smooth Muscl...,"Harman JL, et al. Epigenetic Regulation of Vas...",Vascular inflammation underlies cardiovascular...,NaN,2019/12/9 10:32:47,"Harman JL,Dobnikar L,Chappell J,Stokell BG,Dal...",NaN,Arterioscler. Thromb. Vasc. Biol.,new,Jørgensen HF,"Harman JL, et al. Arterioscler. Thromb. Vasc. ...",NaN
4111,31786140,200114981,HOTTIP lncRNA Promotes Hematopoietic Stem Cell...,"Luo H, et al. HOTTIP lncRNA Promotes Hematopoi...",Long non-coding RNAs (lncRNAs) are critical fo...,NaN,2019/12/9 11:44:08,"Luo H,Zhu G,Xu J,Lai Q,Yan B,Guo Y,Fung TK,Zei...",NaN,Cancer Cell,new,Huang S,"Luo H, et al. Cancer Cell",NaN
4112,31775036,200107408,MLL1 Inhibition and Vitamin D Signaling Cooper...,"Zhang H, et al. MLL1 Inhibition and Vitamin D ...",Dynamic establishment of histone modifications...,NaN,2019/12/9 12:06:00,"Zhang H,Khoa LTP,Mao F,Xu H,Zhou B,Han Y,O'Lea...",NaN,Cell Rep,new,Dou Y,"Zhang H, et al. Cell Rep",NaN
4113,31792383,200128466,Eomes and Brachyury control pluripotency exit ...,"Tosic J, et al. Eomes and Brachyury control pl...",The first lineage specification of pluripotent...,NaN,2019/12/9 12:15:02,"Tosic J,Kim GJ,Pavlovic M,Schröder CM,Mersiows...",NaN,Nat. Cell Biol.,new,Arnold SJ,"Tosic J, et al. Nat. Cell Biol.",NaN
4114,31784538,200122166,Myeloid lineage enhancers drive oncogene syner...,"Braun TP, et al. Myeloid lineage enhancers dri...",Acute Myeloid Leukemia (AML) develops due to t...,NaN,2019/12/9 12:17:26,"Braun TP,Okhovat M,Coblentz C,Carratt SA,Foley...",NaN,Nat Commun,new,Maxson JE,"Braun TP, et al. Nat Commun",NaN

In [156]:
time.strftime("%Y/%m/%d %H:%M:%S", time.localtime())

'2022/11/09 21:19:49'

cell line

In [61]:
tmp = pd.read_csv('celllines_old.txt', sep='\t', header=None)
tmp = tmp.loc[:,1:].copy()
tmp.columns = ['name', 'status', 'comment', 'aliases']
tmp = tmp.sort_values(by='name',ignore_index=True)
tmp = tmp.dropna(subset=['name'])

In [72]:
l = []
for i in tmp['aliases']:
    if pd.isna(i):
        l.append(i)
    else:
        e = [i.rstrip(')').lstrip('(') for i in i.split('|')]
        # e = 
        l.append('|'.join(e))
tmp['aliases'] = l

In [ ]:
tmp.to_csv('../celllines.txt', sep='\t', index=False)

In [77]:
tmp = pd.read_csv('../celllines.txt', sep='\t')

papers

In [50]:
tmp = pd.read_csv('papers_old.txt', sep='\t', header=None)
tmp = tmp.loc[:,1:].copy()
tmp.columns = ['pmid', 'unique_id', 'user_id', 'title', 'reference', 'abstract', 'pub_date', 'collect_date', 'authors', 'last_auth_email', 'journal', 'status', 'comment', 'lab', 'pub_summary']
tmp = tmp.loc[:, ['pmid', 'unique_id', 'title', 'reference', 'abstract', 'pub_date', 'collect_date', 'authors', 'last_auth_email', 'journal', 'status', 'lab', 'pub_summary', 'comment']]

In [51]:
journal = pd.read_csv('journals_old.txt', sep='\t', header = None, index_col=0) 
to_journal = lambda x: journal.loc[x,1]

In [52]:
tmp['journal'] = [to_journal(i) if not pd.isna(i) else np.nan for i in tmp['journal'] ]

In [54]:
tmp.to_csv('papers.txt', sep='\t', index=False)

cell pops

In [87]:
tmp = pd.read_csv('cellpops_old.txt', sep='\t', header=None)
tmp = tmp.loc[:,1:].copy()
tmp.columns = ['name', 'status', 'comment', 'aliases']
tmp = tmp.sort_values(by='name',ignore_index=True)
tmp = tmp.dropna(subset=['name'])

In [88]:
l = []
for i in tmp['aliases']:
    if pd.isna(i):
        l.append(i)
    else:
        e = [i.rstrip(')').lstrip('(') for i in i.split('|')]
        # e = 
        l.append('|'.join(e))
tmp['aliases'] = l

In [89]:
tmp.to_csv('../cellpops.txt', sep='\t', index=False)

cell types

In [78]:
tmp = pd.read_csv('celltypes_old.txt', sep='\t', header=None)
tmp = tmp.loc[:,1:].copy()
tmp.columns = ['name', 'status', 'comment', 'aliases']
tmp = tmp.sort_values(by='name',ignore_index=True)
tmp = tmp.dropna(subset=['name'])

In [79]:
l = []
for i in tmp['aliases']:
    if pd.isna(i):
        l.append(i)
    else:
        e = [i.rstrip(')').lstrip('(') for i in i.split('|')]
        # e = 
        l.append('|'.join(e))
tmp['aliases'] = l

In [80]:
tmp.to_csv('../celltypes.txt', sep='\t', index=False)

disease states

In [81]:
tmp = pd.read_csv('diseasestates_old.txt', sep='\t', header=None)
tmp = tmp.loc[:,1:].copy()
tmp.columns = ['name', 'comment', 'status', 'aliases']
tmp = tmp.loc[:,['name', 'status', 'comment', 'aliases']]
tmp = tmp.sort_values(by='name',ignore_index=True)
tmp = tmp.dropna(subset=['name'])

In [82]:
l = []
for i in tmp['aliases']:
    if pd.isna(i):
        l.append(i)
    else:
        e = [i.rstrip(')').lstrip('(') for i in i.split('|')]
        # e = 
        l.append('|'.join(e))
tmp['aliases'] = l

In [83]:
tmp.to_csv('../diseasestates.txt', sep='\t', index=False)

journal

In [75]:
tmp = pd.read_csv('journals_old.txt', sep='\t', header=None)
tmp = tmp.loc[:,1:].copy()
tmp.columns = ['name', 'issn', 'impact_factor']
tmp = tmp.sort_values(by='name',ignore_index=True)
# tmp = tmp.dropna(subset=['name'])

In [77]:
tmp.to_csv('journals.txt', sep='\t', index=False)

tissue type

In [84]:
tmp = pd.read_csv('tissuetypes_old.txt', sep='\t', header=None)
tmp = tmp.loc[:,1:].copy()
tmp.columns = ['name', 'status', 'comment', 'aliases']
tmp = tmp.sort_values(by='name',ignore_index=True)
# tmp = tmp.dropna(subset=['name'])

In [85]:
l = []
for i in tmp['aliases']:
    if pd.isna(i):
        l.append(i)
    else:
        e = [i.rstrip(')').lstrip('(') for i in i.split('|')]
        # e = 
        l.append('|'.join(e))
tmp['aliases'] = l

In [86]:
tmp.to_csv('../tissuetypes.txt', sep='\t', index=False)

In [79]:
tmp

                       1    2   3    4
0                 Cervix   ok NaN  NaN
1            Bone Marrow   ok NaN  NaN
2                  Colon   ok NaN  NaN
3                   Skin   ok NaN  NaN
4          Mammary Gland   ok NaN  NaN
..                   ...  ...  ..  ...
363           MutuI cell  new NaN  NaN
364       MutuI-LCL cell  new NaN  NaN
365  ALL xenograft cells  new NaN  NaN
366           mesenchyme  new NaN  NaN
367       cardiac tissue  new NaN  NaN

[368 rows x 4 columns]